version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./backend/src/main/resources/database.db:/app/src/main/resources/database.db
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/src/main/resources/database.db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.sqlite.JDBC
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.community.dialect.SQLiteDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      API_KEY_HEADER: x-api-key
      API_KEY: your-secret-api-key
      GRPC_SERVER_HOST: localhost
      GRPC_SERVER_PORT: 9090

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MODE: development
    ports:
      - "5173:80"
    environment:
      VITE_APP_API_KEY_HEADER: x-api-key
      VITE_APP_API_KEY: your-secret-api-key
      VITE_APP_API_BASE_URL: http://localhost:8080
