package com.kaarelkaasla.klaustestassignment.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a rating category. Maps to the "rating_categories" table in the database.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity(name = "rating_categories")
public class RatingCategory {

    /**
     * Unique identifier for the rating category. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the rating category.
     */
    private String name;

    /**
     * The weight of the rating category, used for calculating weighted scores.
     */
    private double weight;
}
