package com.kaarelkaasla.klaustestassignment.entity;

import com.kaarelkaasla.klaustestassignment.config.DateAttributeConverter;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * Entity class representing a rating. Maps to the "ratings" table in the database.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity(name = "ratings")
public class Rating {

    /**
     * Unique identifier for the rating. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The rating value given by the reviewer.
     */
    private int rating;

    /**
     * The identifier of the ticket associated with this rating.
     */
    private int ticketId;

    /**
     * The identifier of the rating category.
     */
    private int ratingCategoryId;

    /**
     * The identifier of the reviewer.
     */
    private int reviewerId;

    /**
     * The identifier of the reviewee.
     */
    private int revieweeId;

    /**
     * The date and time when the rating was created. Converted using {@link DateAttributeConverter} and stored as text
     * in the database.
     */
    @Convert(converter = DateAttributeConverter.class)
    @Column(name = "created_at", columnDefinition = "TEXT")
    private Date createdAt;
}
